// Generated by CoffeeScript 1.6.3
(function() {
  var RS, socket;

  RS = require("raw-socket");

  socket = RS.createSocket({
    protocol: RS.Protocol.ICMP
  });

  socket.on("message", function(buffer, source) {
    if (buffer[20] === 8) {
      console.log("recieve " + buffer.length + " from " + source);
      return console.log("full package ", buffer.toString("base64"));
    }
  });

}).call(this);
